# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ce2ef976a0f09abc150f160098db0ab049aae713590e3f58313bfe70cbd1f4b6e5660c467b80171e9355bf1bdb335dbce4375f424adcb15258bef8298babdc0

test:
  secret_key_base: 7cbb886551c024cb84ca955bfbb357716e758c21f1f12643a172cfbe7f17f5c876480315f3b26abf0095cc5d2de12f6e3e38d0e7124160be17e039d104111a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
